<MyWidget>:
    orientation: "vertical"

    MDBoxLayout:
        id: bxI
        orientation: "horizontal"
        size_hint_y: 0.2

        MDLabel:
            text: "IP do Servidor"

        MDTextField:
            id: txt_ip_servidor
            text: "127.0.0.1"

    MDBoxLayout:
        id: bxIII
        orientation: "horizontal"
        size_hint_y: 0.2

        MDLabel:
            text: "Porta"

        MDTextField:
            id: txt_porta
            text: "502"

    MDBoxLayout:
        id: bxEndereco
        orientation: "horizontal"
        size_hint_y: 0.2

        MDLabel:
            text: "Endereço"

        MDTextField:
            id: txt_endereco

    MDBoxLayout:
        id: bxValor
        orientation: "horizontal"
        size_hint_y: 0.2

        MDLabel:
            text: "Valor"

        MDTextField:
            id: txt_valor

    MDBoxLayout:
        id: bxBit
        orientation: "horizontal"
        size_hint_y: 0.2

        MDLabel:
            text: "Bit"

        MDTextField:
            id: txt_bit

    MDBoxLayout:
        id: bxVI
        orientation: "horizontal"
        size_hint_y: 0.2

        MDLabel:
            text: "Register"

        MDLabel:
            text: "Float"

        MDLabel:
            text: "Bits"

        MDLabel:
            text: "Coil"

        MDLabel:
            text: "Recorrente"

    MDBoxLayout:
        id: bxIV
        orientation: "horizontal"
        size_hint_y: 0.2

        MDCheckbox:
            id: chk_register
            group: "tipo"
            active: True

        MDCheckbox:
            id: chk_float
            group: "tipo"

        MDCheckbox:
            id: chk_bits
            group: "tipo"

        MDCheckbox:
            id: chk_coil
            group: "tipo"

        MDCheckbox:
            id: chk_recorrente
            on_active: root.toggle_recorrente(self.active)

    MDBoxLayout:
        id: bxV
        orientation: "horizontal"
        size_hint_y: 0.2

        MDRaisedButton:
            text: "Conectar"
            on_release: root.conectar()

        MDRaisedButton:
            text: "Ler"
            on_release: root.ler()

        MDRaisedButton:
            text: "Escrever"
            on_release: root.escrever()

    MDBoxLayout:
        orientation: "horizontal"
        size_hint_y: 0.2

        MDLabel:
            id: lbl_resultado
            text: "Resultado"
