<MyWidget>:
    orientation: "vertical"
    MDBoxLayout:
        id: bxI
        orientation: "horizontal"
        size_hint_y: 0.2

        MDLabel:
            text: "IP do Servidor"

        MDTextField:
            text: "127.0.0.1"
    MDBoxLayout:
        id: bxII
        orientation: "horizontal"
        size_hint_y: 0.2

        MDLabel:
            text: "IP do Cliente"

        MDTextField:
            text: "127.0.0.1"
    MDBoxLayout:
        id: bxIII
        orientation: "horizontal"
        size_hint_y: 0.2

        MDLabel:
            text: "Porta"

        MDTextField:
            text: "502"
    MDBoxLayout:
        id: bxVI
        size_hint_y: 0.2
        orientation: "horizontal"

        MDLabel:
            text: "Box 1"
            size_hint_y: 0.2
            pos_hint: {'center_y':0.2}
        MDLabel:
            text: "Box 2"
            pos_hint: {'center_y':0.2}
        MDLabel:
            text: "Box 3"
            pos_hint: {'center_y':0.2}
        MDLabel:
            text: "Box 4"
            pos_hint: {'center_y':0.2}
        MDLabel:
            text: "Box 5"
            pos_hint: {'center_x':0.2}
        MDLabel:
            text: "Box 6"
            pos_hint: {'center_y':0.2}

    MDBoxLayout:
        id: bxIV
        orientation: "horizontal"
        size_hint_y: 0.2

        MDCheckbox:

        MDCheckbox:

        MDCheckbox:

        MDCheckbox:

        MDCheckbox:

        MDCheckbox:

    MDBoxLayout:
        id: bxV
        orientation: "horizontal"
        size_hint_y: 0.2

        MDRaisedButton:
            text: "Ler"

        MDRaisedButton:
            text: "Escrever"
        MDLabel:
            text: "Valor aqui"
            size_hint_y: (0.2)